version: "3"
services:
  springBootApp:
    image: com.mostafa/mostafa.assessment:0.0.1-SNAPSHOT
    container_name: mostafa-assessment-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mostafa-assessment-db:5432/file_management
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8080:8080"
    networks:
      - network
    depends_on:
      - postgresDb
    restart: on-failure

  postgresDb:
    image: postgres:16.0-alpine
    container_name: mostafa-assessment-db
    ports:
      - "5434:5432"
    networks:
      - network
    volumes:
      - volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=file_management

networks:
  network:

volumes:
  volume: